apiVersion: v1
kind: Service
metadata:
  name: api-lakehouse-backend
  namespace: {{ .Values.platform_namespace }}
  labels:
    app: api-lakehouse-backend
spec:
  ports:
  - port: 8080
  selector:
    app: api-lakehouse-backend
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: api-lakehouse
#  namespace: {{ .Values.platform_namespace }}
#  labels:
#    app: api-lakehouse
#spec:
#  ports:
#  - port: 8080
#  selector:
#    app: api-lakehouse
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: api-log-manager
#  namespace: {{ .Values.platform_namespace }}
#  labels:
#    app: api-log-manager
#spec:
#  ports:
#  - port: 8080
#  selector:
#    app: api-log-manager
---
apiVersion: v1
kind: Service
metadata:
  name: service-scheduler
  namespace: {{ .Values.platform_namespace }}
  labels:
    app: service-scheduler
spec:
  ports:
  - port: 8080
  selector:
    app: service-scheduler