apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: api-lakehouse-backend
  namespace: {{ .Values.platform_namespace }}
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-lakehouse-backend
  targetCPUUtilizationPercentage: 50
#---
#apiVersion: autoscaling/v1
#kind: HorizontalPodAutoscaler
#metadata:
#  name: api-lakehouse
#  namespace: {{ .Values.platform_namespace }}
#spec:
#  maxReplicas: 10
#  minReplicas: 1
#  scaleTargetRef:
#    apiVersion: apps/v1
#    kind: Deployment
#    name: api-lakehouse
#  targetCPUUtilizationPercentage: 50
#---
#apiVersion: autoscaling/v1
#kind: HorizontalPodAutoscaler
#metadata:
#  name: api-log-manager
#  namespace: {{ .Values.platform_namespace }}
#spec:
#  maxReplicas: 10
#  minReplicas: 1
#  scaleTargetRef:
#    apiVersion: apps/v1
#    kind: Deployment
#    name: api-log-manager
#  targetCPUUtilizationPercentage: 50
