apiVersion: v1
kind: ServiceAccount
metadata:
  name: hai-service-account
  namespace: {{ .Values.platform_namespace }}
imagePullSecrets:
- name: nirnayai-cred
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hai-sa-crb
roleRef:
  kind:  ClusterRole
  name:  cluster-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: hai-service-account
  namespace: {{ .Values.platform_namespace }}

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: hai-workers-service-account
  namespace: {{ .Values.workers_namespace }}
imagePullSecrets:
- name: nirnayai-cred
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hai-workers-sa-crb
roleRef:
  kind:  ClusterRole
  name:  cluster-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: hai-workers-service-account
  namespace: {{ .Values.workers_namespace }}
