apiVersion: v1
kind: Secret
metadata:
  name: nirnayai-cred
  namespace: {{ .Values.platform_namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "dockerRegistryImagePullSecret" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: nirnayai-cred
  namespace: {{ .Values.workers_namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "dockerRegistryImagePullSecret" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: hai-storage-secret
  namespace: {{ .Values.platform_namespace }}
type: Opaque
data:
  storage_backend: {{ .Values.storage_config.storage_backend | b64enc }}
  access_key: {{ .Values.storage_config.storage_access_key | b64enc }}
  secret_key: {{ .Values.storage_config.storage_secret_key | b64enc }}
  server: {{ .Values.storage_config.storage_server | b64enc }}
  storage_bucket_structured: {{ .Values.storage_config.storage_bucket_structured | b64enc }}
  storage_bucket_unstructured: {{ .Values.storage_config.storage_bucket_unstructured | b64enc }}
  storage_bucket_notebooks: {{ .Values.storage_config.storage_bucket_notebooks | b64enc }}
