releases:

  - name: minio-operator
    namespace: minio-operator
    chart: minio/operator
    version: 4.5.5
    condition: minio.enabled
    wait: true
    waitForJobs: true

repositories:
  - name: minio
    url: https://operator.min.io/
