lakehouse:
  registry: "localhost:32000"
  tag: "latest"
  docker_user_name: "test"
  docker_password: "test"

minio:
  enabled: false
  server: "minio.hai-minio:80"

s3:
  server: "s3.amazonaws.com"

storage_config:
  storage_bucket_structured: "lakehouse-structured"
  storage_bucket_unstructured: "lakehouse-unstructured"
  storage_bucket_notebooks: "lakehouse-notebooks"
  accessKey: "AKIAYFVPBHBUJBGZFQFX"
  secretKey: "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"

ingress:
  app_host_name: app.nirnay.com
  tls_secret_name: app-tls-secret
