repositories:
- name: incubator
  url: https://charts.helm.sh/incubator

releases:
- name: trino-nginx
  chart: incubator/raw
  namespace: hai-trino
  values:
  - resources:
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: nginx-conf
      data:
        nginx.conf: |
          user nginx;
          worker_processes  1;
          events {
            worker_connections  10240;
          }
          http {
            server {
                listen       443 ssl;
                ssl_certificate     /tmp/ssl/cert.pem;
                ssl_certificate_key /tmp/ssl/key.pem;

                location / {
                  proxy_set_header        Host $host;
                  proxy_set_header        X-Real-IP $remote_addr;
                  proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header        X-Forwarded-Proto https;

                  proxy_pass          http://hai-trino.hai-trino.svc.cluster.local:8080;
              }
            }
          }
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: trino-internal
      spec:
        selector:
          matchLabels:
            app: trino-internal
        replicas: 1
        template:
          metadata:
            labels:
              app: trino-internal
          spec:
            containers:
              - name: nginx
                image: nginx
                ports:
                  - containerPort: 443
                volumeMounts:
                  - name: nginx-conf
                    mountPath: /etc/nginx/nginx.conf
                    subPath: nginx.conf
                    readOnly: true
                  - name: ssl-folder
                    mountPath: /tmp/ssl
            initContainers:
              - name: ssl-init
                image: wolmi/tools:v1.1.0
                command: [ "sh", "-c", 'openssl req -nodes -x509 -newkey rsa:4096 -keyout /tmp/ssl/key.pem -out /tmp/ssl/cert.pem -days 365 -subj "/C=DE/ST=NRW/L=Berlin/O=My Inc/OU=DevOps/CN=www.example.com/emailAddress=dev@www.example.com"' ]
                volumeMounts:
                  - name: ssl-folder
                    mountPath: /tmp/ssl
            volumes:
              - name: nginx-conf
                configMap:
                  name: nginx-conf
                  items:
                    - key: nginx.conf
                      path: nginx.conf
              - name: ssl-folder
                emptyDir: { }
    - apiVersion: v1
      kind: Service
      metadata:
        name: trino-internal
      spec:
        type: ClusterIP
        ports:
          - port: 443
            protocol: TCP
            targetPort: 443
        selector:
          app: trino-internal
